<a href="https://colab.research.google.com/github/MadhulikaSuresh/05022025/blob/main/22Dec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
c=a+1
print(c)

[[ 2  3  4  5]
 [ 3  5  6  7]
 [11 21 40  4]]


In [ ]:
#math
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
c=a/3
print(c)

[[ 0.33333333  0.66666667  1.          1.33333333]
 [ 0.66666667  1.33333333  1.66666667  2.        ]
 [ 3.33333333  6.66666667 13.          1.        ]]


In [ ]:
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
b= np.array([[11,21,31,4],[21,14,5,6],[10,210,319,31]])
c=a+1
add=a+b+c
print(add)

[[ 14  26  38  13]
 [ 26  23  16  19]
 [ 31 251 398  38]]


In [ ]:
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
b= np.array([[11,21,31,4],[21,14,5,6],[10,210,319,31]])
c=a+b
print(c)
a=a>b
print(a)


[[ 12  23  34   8]
 [ 23  18  10  12]
 [ 20 230 358  34]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [ ]:
#slice
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])

c=a[0,0]
print(c)

1


In [ ]:
#slice
import numpy as np#3x4
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])

c=a[0,0]
c1=a[0,1]
c2=a[0,2]
c3=a[0,3]
d1=a[1,0]
d2=a[1,1]
d3=a[1,2]
d4=a[1,3]
e1=a[2,0]
e2=a[2,1]
e3=a[2,2]
e4=a[2,3]
print(c)
print(c1)
print(c2)
print(d1)
print(d2)
print(d3)
print(d4)
print(e1)
print(e2)
print(e3)
print(e4)

1
2
3
2
4
5
6
10
20
39
3


In [ ]:
import numpy as np#sort
x = np.array([[10,2,3,4],[20,4,5,6],[10,20,39,3]])
print("Original mat:")
print(x)
print("sort:")
y = np.sort(x)
print(y)

Original mat:
[[10  2  3  4]
 [20  4  5  6]
 [10 20 39  3]]
sort:
[[ 2  3  4 10]
 [ 4  5  6 20]
 [ 3 10 20 39]]


In [ ]:
import numpy as np#sort
x = np.array([[10,2,3,4],[20,4,5,6],[10,20,39,3]])
print("Original mat:")
print(x)

Original mat:
[[10  2  3  4]
 [20  4  5  6]
 [10 20 39  3]]


In [ ]:
y = np.min(x)
z=np.max(x)
a=np.mean(x)
print("Min",y)
print("Average",a)
print("max",z)

Min 2
Average 10.5
max 39


In [ ]:
a = 3000
b = 400
if b > a:
  print("b is greater than a")

In [ ]:
#error sim
a = 33
b = 200
if b > a:
print("b is greater than a") # you will get an error


IndentationError: expected an indented block after 'if' statement on line 4 (<ipython-input-13-8cc2579db0bc>, line 5)

In [ ]:
#ELSE IF
a = 433
b = 433
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a and b are equal


In [ ]:
a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
elif a > b:
  print("a geater")
else:
  print("a is greater than b")

a geater


In [ ]:
# AND if c is greater than a:
a = 2
b = 2
c = 2
if a > b and a > c:
  print("a is greater")
elif a == b and a == c:
  print("all are equal")
elif b > a and b >c:
  print("b is greater")
else:
  print("else")

all are equal


In [ ]:
# AND if c is greater than a:
a = 2
b = 3
c = 2
if a > b and a > c:
  print("a is greater")
elif a == b and a == c:
  print("all are equal")
elif b > a and b >c:
  print("b is greater")
else:
  print("else")

b is greater


In [ ]:
# AND if c is greater than a:
a = 3
b = 2
c = 3
if a > b and a > c:
  print("a is greater")
elif a == b and a == c:
  print("all are equal")
elif b > a and b >c:
  print("b is greater")
else:
  print("else")

else


In [ ]:
# Define user ID and password
user_id = "abcd"
password = "1234"

input_user_id = input("Enter user ID: ")
input_password = input("Enter password: ")

# Check if the user ID and password are correct
if input_user_id == user_id and input_password == password:

    print("Access granted. Welcome to the module!")
else:

    print("Access denied. Incorrect user ID or password.")

Enter user ID: abcd
Enter password: 1234
Access granted. Welcome to the module!


In [ ]:
score1 = int(input("Enter score1: "))
if score1 > 90:
    print("Student grade is A")
elif score1 >= 80 and score1 <= 89:
    print("Student grade is B")
elif score1 >= 70 and score1 <= 79:
    print("Student grade is C")
elif score1 >= 60 and score1 <= 69:
    print("Student grade is D")
else:
    print("Student grade is F")

Enter score1: 90
Student grade is F


In [ ]:
age0 = int(input("Enter age: "))
if age0 <= 2:
    print("Infant")
elif 3 <= age0 <= 12:
    print("Child")
elif 13 <= age0 <= 19:
    print("Teenager")
elif 20 <= age0 <= 59:
    print("Adult")
else:
    print("Senior Citizen")

Enter age: 60
Senior Citizen


In [ ]:
Weight0 = float(input("Enter weight: "))

if Weight0 < 18.5:
    print("Underweight")
elif 18.5 <= Weight0 <= 24.9:
    print("Normal weight")
elif 25 <= Weight0 <= 29.9:
    print("Overweight")
elif 30 <= Weight0 <= 100:
    print("Obese")
else:
    print("null")

Enter weight: 25.5
Overweight


In [ ]:
#for
for x in range(5):  #start at 0 end before 5 increment by 1
    print(x)

for x in range(5):  #start at 0 end before 5 increment by 1
    print("hi")

for x in range(5):  #start at 0 end before 5 increment by 1
    a=int(input("Enter salary"))
    print("salary=",a)
    print(x)


0
1
2
3
4
hi
hi
hi
hi
hi
Enter salary10000
salary= 10000
0
Enter salary10000
salary= 10000
1
Enter salary1000
salary= 1000
2
Enter salary1
salary= 1
3
Enter salary23
salary= 23
4


In [ ]:
# Prints out 3,5
for x in range(3, 100, 2):   #start at 3 end before 100 increment by 2
    print(x)

3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99


In [ ]:
def add():
   x=2
   y=4
   c=x+y
   print("add=",c)

def sub():
    x=2
    y=4
    c1=x-y
    print("sub=",c1)

z=add()
z1=sub()
print(z)


add= 6
sub= -2
None


In [ ]:
def add():
   x=2
   y=4
   c=x+y
   print("add=",c)

def sub():
    x=2
    y=4
    c1=x-y
    print("sub=",c1)

z=add()

add= 6


In [ ]:
def add():
   x=2
   y=4
   c=x+y
   print("add=",c)
   return c
def sub():
    x=2
    y=4
    c1=x-y
    print("sub=",c1)
    return c1
z=add()
print(z)
z1=sub()
print(z1)

add= 6
6
sub= -2
-2


In [ ]:
# Initialize a variable
number = 1

while number <= 10:
    print(number)
    number = number+1

1
2
3
4
5
6
7
8
9
10


In [ ]:
# the test condition is always True
age = 21
while age > 18:
    print('You can vote')
    break

You can vote


In [ ]:
age = 12

# the test condition is always True
while age > 18:
    print('You can vote')
    break
else:
   print("you are not eligible to vote")

you are not eligible to vote
